# Generated by Django 4.0.1 on 2022-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content2',
            field=models.IntegerField(),
        ),
    ]
