# Generated by Django 4.0.1 on 2022-02-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stude', to='core.student')),
            ],
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
